packages:
  - apps/*
  - packages/*
  - packages/adapters/*
  - testing/*
minimumReleaseAgeExclude:
  - '@hono/node-server@2.1.4'
allowBuilds:
  protobufjs: false
  prisma: true
  '@prisma/engines': true
  msgpackr-extract: false
