import type { CodeOwnership } from '@git-migrator/canonical';
import { describe, expect, it } from 'vitest';
import { parseCodeowners, renderCodeowners } from './facets/access.ts';
import { all, type Harness, setup } from './harness.test.ts';

const FILES = { 'README.md': '# hi\n', 'src/a.txt': 'a\n' };

async function withRepo(files: Record<string, string> | null = FILES) {
  const h = await setup();
  const repo = h.fake.state.addRepository('acme', {
    name: 'r',
    private: true,
    ...(files === null ? {} : { files }),
  });
  return { h, repo };
}

const request = (
  extra: Partial<{ files: { path: string; content: string }[]; title: string; body: string }> = {},
) => ({
  purpose: 'ci',
  branch: 'git-migrator/ci',
  title: 'Add CI',
  body: 'Generated by git-migrator.',
  files: [{ path: '.github/workflows/ci.yml', content: 'name: ci\n' }],
  ...extra,
});

function writer(h: Harness) {
  const w = h.conn.changeRequests;
  if (!w) throw new Error('no writer');
  return w;
}

describe('Change Request writer', () => {
  it('[LIF-047] creates the branch, one commit by git-migrator and a pull request', async () => {
    const { h, repo } = await withRepo();
    const result = await writer(h).upsert(h.repo('r'), request());
    expect(result.state).toBe('open');
    expect(result.url).toMatch(/\/pull\/1$/);
    expect(result.mutations.map((m) => `${m.action}:${String(m.resourceRef.kind)}`)).toEqual([
      'create:ref',
      'update:ref',
      'create:change-request',
    ]);
    expect(repo.pulls).toHaveLength(1);
    expect(repo.pulls[0]?.headRef).toBe('git-migrator/ci');
    const sha = repo.git.resolve('refs/heads/git-migrator/ci') as string;
    const commit = repo.git.commits.get(sha);
    expect(JSON.stringify(commit)).toContain('noreply@git-migrator.invalid');
    expect(await writer(h).status(h.repo('r'), 'ci')).toBe('open');
  });

  it('[LIF-047] an open Change Request is updated, not duplicated, and unchanged input writes nothing', async () => {
    const { h, repo } = await withRepo();
    await writer(h).upsert(h.repo('r'), request());
    const same = await writer(h).upsert(h.repo('r'), request());
    expect(same.mutations).toEqual([]);
    expect(repo.pulls).toHaveLength(1);
    const changed = await writer(h).upsert(
      h.repo('r'),
      request({
        title: 'Add CI v2',
        files: [{ path: '.github/workflows/ci.yml', content: 'name: ci2\n' }],
      }),
    );
    expect(changed.state).toBe('open');
    expect(changed.mutations.map((m) => m.action)).toEqual(['update', 'update']);
    expect(repo.pulls).toHaveLength(1);
    expect(repo.pulls[0]?.title).toBe('Add CI v2');
  });

  it('[LIF-047] a merged Change Request is never reopened', async () => {
    const { h, repo } = await withRepo();
    await writer(h).upsert(h.repo('r'), request());
    const pull = repo.pulls[0];
    if (pull) {
      pull.state = 'closed';
      pull.merged = true;
      pull.closedAt = Date.now();
    }
    const again = await writer(h).upsert(h.repo('r'), request({ title: 'other' }));
    expect(again).toMatchObject({ state: 'merged', mutations: [] });
    expect(await writer(h).status(h.repo('r'), 'ci')).toBe('merged');
    expect(repo.pulls).toHaveLength(1);
  });

  it('[LIF-047] content already on the default branch needs no Change Request', async () => {
    const { h, repo } = await withRepo({ ...FILES, '.github/workflows/ci.yml': 'name: ci\n' });
    const result = await writer(h).upsert(h.repo('r'), request());
    expect(result).toMatchObject({ state: 'merged', mutations: [] });
    expect(repo.pulls).toHaveLength(0);
    expect(repo.git.resolve('refs/heads/git-migrator/ci')).toBeUndefined();
    expect(await writer(h).status(h.repo('r'), 'ci')).toBe('none');
  });

  it('[LIF-047] an empty repository (no default branch) is a conflict', async () => {
    const { h } = await withRepo(null);
    await expect(writer(h).upsert(h.repo('r'), request())).rejects.toMatchObject({
      code: 'conflict',
    });
  });

  it('[LIF-047] the branch must be git-migrator/<purpose>', async () => {
    const { h } = await withRepo();
    await expect(
      writer(h).upsert(h.repo('r'), request({}) && { ...request(), branch: 'other' }),
    ).rejects.toMatchObject({
      code: 'invalid',
    });
  });

  it('[LIF-047] close closes an open one and reports the mutation; closing again is a no-op', async () => {
    const { h, repo } = await withRepo();
    await writer(h).upsert(h.repo('r'), request());
    const closed = await writer(h).close(h.repo('r'), 'ci');
    expect(closed).toHaveLength(1);
    expect(repo.pulls[0]?.state).toBe('closed');
    expect(await writer(h).status(h.repo('r'), 'ci')).toBe('closed');
    expect(await writer(h).close(h.repo('r'), 'ci')).toEqual([]);
  });

  it('[LIF-047] a foreign branch holding a human commit is refused with no writes', async () => {
    const { h, repo } = await withRepo();
    h.fake.state.addBranch(
      repo,
      'git-migrator/ci',
      { 'human.txt': 'mine\n' },
      {
        from: 'main',
        message: 'human work',
      },
    );
    const sha = repo.git.resolve('refs/heads/git-migrator/ci');
    const before = h.requests.length;
    await expect(writer(h).upsert(h.repo('r'), request())).rejects.toMatchObject({
      code: 'conflict',
      message: expect.stringContaining('git-migrator/ci'),
    });
    // Only repository writes count; the installation token exchange is a POST of its own.
    const writes = h.requests
      .slice(before)
      .filter((r) => r.method !== 'GET' && r.url.includes('/repos/'));
    expect(writes).toHaveLength(0);
    expect(repo.git.resolve('refs/heads/git-migrator/ci')).toBe(sha);
    expect(repo.pulls).toHaveLength(0);
  });

  it('[LIF-047] a framework-authored branch with no open request is adopted, with before === after', async () => {
    const { h, repo } = await withRepo();
    await writer(h).upsert(h.repo('r'), request());
    const pull = repo.pulls[0];
    if (pull) pull.state = 'closed';
    const again = await writer(h).upsert(h.repo('r'), request({ title: 'Add CI again' }));
    const adopted = again.mutations.find((m) => m.resourceRef.adopted === true);
    expect(adopted).toMatchObject({ action: 'create' });
    expect(adopted?.before).toEqual(adopted?.after);
    expect(again.state).toBe('open');
    expect(repo.pulls).toHaveLength(2);
  });

  it('[LIF-047] a Change Request opened despite a lost response is read back and ledgered', async () => {
    const h = await setup({
      intercept: async (r) => {
        if (r.method !== 'POST' || !r.url.endsWith('/pulls')) return undefined;
        // The provider accepts the request, then the response is lost.
        await h.fake.app.fetch(r);
        return new Response('{"message":"Service Unavailable"}', {
          status: 503,
          headers: { 'content-type': 'application/json' },
        });
      },
    });
    const repo = h.fake.state.addRepository('acme', { name: 'r', files: FILES });
    const result = await writer(h).upsert(h.repo('r'), request());
    expect(result.state).toBe('open');
    expect(result.mutations.map((m) => `${m.action}:${String(m.resourceRef.kind)}`)).toContain(
      'create:change-request',
    );
    expect(repo.pulls).toHaveLength(1);
  });

  it('[LIF-047] writes do not retry', async () => {
    const { h } = await withRepo();
    await writer(h).upsert(h.repo('r'), request());
    const posts = h.requests.filter((r) => r.method === 'POST' && r.url.endsWith('/pulls'));
    expect(posts).toHaveLength(1);
  });
});

describe('code-ownership', () => {
  it('[FAC-COD] renders and parses CODEOWNERS', () => {
    const doc: CodeOwnership = {
      owners: [
        {
          pattern: '*',
          principals: [
            { principal: { kind: 'identity', id: '1' } },
            { principal: { kind: 'group', id: '2' } },
          ],
        },
        { pattern: 'docs/', principals: [] },
      ],
    };
    const text = renderCodeowners(doc, (p) => (p.kind === 'group' ? '@acme/devs' : '@bob'));
    expect(text).toContain('* @bob @acme/devs');
    expect(parseCodeowners(`${text}\n# comment\n* @last # trailing\n`)).toEqual([
      { pattern: '*', owners: ['@last'] },
      { pattern: 'docs/', owners: [] },
    ]);
  });

  it('[FAC-COD] reads owners from .github/CODEOWNERS and resolves logins and teams to ids', async () => {
    const h = await setup();
    const s = h.fake.state;
    const bob = s.addMember('acme', 'bob');
    const team = s.addTeam('acme', { name: 'devs' });
    s.addRepository('acme', {
      name: 'r',
      files: {
        'README.md': 'x',
        '.github/CODEOWNERS': '* @bob @acme/devs @ghost someone@example.test\n',
      },
    });
    const read = await h.conn.facets['code-ownership']?.read(h.ctx, h.target('r'));
    expect(read?.data).toEqual({
      owners: [
        {
          pattern: '*',
          principals: [
            { principal: { kind: 'group', id: String(team.id) } },
            { principal: { kind: 'identity', id: String(bob.id) } },
          ],
        },
      ],
    });
    expect(read?.warnings.map((w) => w.code).sort()).toEqual([
      'code-ownership.owner-unrepresentable',
      'code-ownership.owner-unresolved',
    ]);
  });

  it('[FAC-COD] apply delivers CODEOWNERS through a Change Request and is idempotent', async () => {
    const h = await setup();
    const s = h.fake.state;
    const bob = s.addMember('acme', 'bob');
    const team = s.addTeam('acme', { name: 'devs' });
    const repo = s.addRepository('acme', { name: 'r', files: FILES });
    const d = h.conn.facets['code-ownership'];
    const desired: CodeOwnership = {
      owners: [
        {
          pattern: '*',
          principals: [
            { principal: { kind: 'group', id: String(team.id) } },
            { principal: { kind: 'identity', id: String(bob.id) } },
          ],
        },
      ],
    };
    const current = (await d?.read(h.ctx, h.target('r')))?.data;
    const out = await all(d?.apply?.(h.ctx, h.target('r'), desired, current, []));
    expect(out.length).toBeGreaterThan(0);
    // Every record is the code-ownership facet's and covers /owners (LIF-045, ADP-012), while the
    // resource kinds rollback dispatches on are unchanged (LIF-077).
    expect(out.map((m) => [m.facetKey, m.paths])).toEqual(
      out.map(() => ['code-ownership', ['/owners']]),
    );
    expect(out.map((m) => String(m.resourceRef.kind))).toContain('change-request');
    expect(out.find((m) => m.resourceRef.kind === 'change-request')?.resourceRef.purpose).toBe(
      'codeowners',
    );
    expect(repo.pulls).toHaveLength(1);
    // Not merged yet: the default branch still has no CODEOWNERS, the open request is updated in place.
    const again = await all(d?.apply?.(h.ctx, h.target('r'), desired, current, []));
    expect(again).toEqual([]);
    expect(repo.pulls).toHaveLength(1);
    // After the merge the target reads equal and nothing more happens.
    const branchSha = repo.git.resolve('refs/heads/git-migrator/codeowners');
    expect(branchSha).toBeDefined();
  });
});

describe('code-ownership partial writes', () => {
  it('[LIF-045] a failed Change Request still yields the records written before the failure', async () => {
    const h = await setup({
      intercept: (r) =>
        r.method === 'POST' && r.url.endsWith('/pulls')
          ? new Response('{"message":"Validation Failed"}', {
              status: 422,
              headers: { 'content-type': 'application/json' },
            })
          : undefined,
    });
    const s = h.fake.state;
    const bob = s.addMember('acme', 'bob');
    s.addRepository('acme', { name: 'r', files: FILES });
    const d = h.conn.facets['code-ownership'];
    const desired: CodeOwnership = {
      owners: [
        { pattern: '*', principals: [{ principal: { kind: 'identity', id: String(bob.id) } }] },
      ],
    };
    const yielded: string[] = [];
    const keys = new Set<string>();
    let thrown: unknown;
    try {
      for await (const m of d?.apply?.(h.ctx, h.target('r'), desired, null, []) ?? []) {
        keys.add(`${m.facetKey}:${m.paths.join(',')}`);
        yielded.push(`${m.action}:${String(m.resourceRef.kind)}`);
      }
    } catch (error) {
      thrown = error;
    }
    expect(thrown).toMatchObject({ code: 'invalid' });
    expect(yielded).toEqual(['create:ref', 'update:ref']);
    expect([...keys]).toEqual(['code-ownership:/owners']);
  });
});
